#ifndef INTR_H_INCLUDED
#define INTR_H_INCLUDED

#define SOFTVEC_TYPE_NUM	3

#define SOFTVEC_TYPE_SOFTERR	0
#define SOFTVEC_TYPE_SYSCALL	1
#define SOFTVEC_TYPE_SERINTR	2

#endif /* INTR_H_INCLUDED */
